version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      env_global-routing-network:
        aliases:
          - routing-zookeeper
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: routing-zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    networks:
      env_global-routing-network:
        aliases:
          - routing-test-kafka-service

networks:
  env_global-routing-network:
    external: true
